version: "3.8"
services:
    www:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: conteiner_apache
        links:
            - db
        depends_on:
            - db
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
    db:
        container_name: conteiner_mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
        ports:
            - "6033:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: conteiner_phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent:
